#!/bin/bash

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2019-present Team LibreELEC (https://libreelec.tv)

. config/options $1

mcopy "$RELEASE_DIR/3rdparty/bootloader/aml_autoscript" :: 2>&1 > /dev/null || true
mcopy "$RELEASE_DIR/3rdparty/bootloader/aml_autoscript.zip" :: 2>&1 > /dev/null || true
mcopy "$RELEASE_DIR/3rdparty/bootloader/s905_autoscript" :: 2>&1 > /dev/null || true
mcopy "$RELEASE_DIR/3rdparty/bootloader/dtb" :: 2>&1 > /dev/null || true
mcopy "$RELEASE_DIR/3rdparty/bootloader/install2emmc.sh" :: 2>&1 > /dev/null || true
mcopy "$RELEASE_DIR/3rdparty/bootloader/ddbr-backup.sh" :: 2>&1 > /dev/null || true
mcopy "$RELEASE_DIR/3rdparty/bootloader/ddbr-restore.sh" :: 2>&1 > /dev/null || true

if [ -f "$RELEASE_DIR/3rdparty/bootloader/boot.ini" ]; then
  mcopy "$RELEASE_DIR/3rdparty/bootloader/boot.ini" :: 2>&1 > /dev/null || true
fi

mkdir -p "${LE_TMP}/extlinux"

cat << EOF > "${LE_TMP}/extlinux/extlinux.conf"
LABEL ${DISTRO}
  LINUX /${KERNEL_NAME}
  FDT /dtb/${DTB_NAME}
  APPEND boot=LABEL=LIBREELEC disk=LABEL=STORAGE quiet ${EXTRA_CMDLINE}
EOF

mcopy -s "${LE_TMP}/extlinux" ::

cat << EOF > "${LE_TMP}/uEnv.ini"
dtb_name=/dtb/${DTB_NAME}
bootargs=boot=LABEL=LIBREELEC disk=LABEL=STORAGE quiet ${EXTRA_CMDLINE}
EOF
mcopy -s "${LE_TMP}/uEnv.ini" ::
