#!/bin/bash

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2019-present Team LibreELEC (https://libreelec.tv)

mkdir -p "$RELEASE_DIR/3rdparty/bootloader"
  cp -a $(get_build_dir aml_autoscript)/* $RELEASE_DIR/3rdparty/bootloader

  if [ -f "$ROOT/projects/$PROJECT/devices/$DEVICE/bootloader/boot.ini" ]; then
    cp -a $ROOT/projects/$PROJECT/devices/$DEVICE/bootloader/boot.ini $RELEASE_DIR/3rdparty/bootloader
  fi

  if [ -f "$ROOT/projects/$PROJECT/devices/$DEVICE/bootloader/u-boot.bin" ]; then
    cp -a $ROOT/projects/$PROJECT/devices/$DEVICE/bootloader/u-boot.bin $RELEASE_DIR/3rdparty/bootloader
  fi

  if [ -f "$ROOT/projects/$PROJECT/devices/$DEVICE/bootloader/u-boot.bin.sd.bin" ]; then
    cp -a $ROOT/projects/$PROJECT/devices/$DEVICE/bootloader/u-boot.bin.sd.bin $RELEASE_DIR/3rdparty/bootloader
  fi

mkdir -p "$RELEASE_DIR/3rdparty/bootloader/dtb"
  case ${DEVICE:-$PROJECT} in
    AMLGX)
      cp -a $(get_build_dir linux)/arch/$TARGET_KERNEL_ARCH/boot/dts/amlogic/*gxbb*.dtb $RELEASE_DIR/3rdparty/bootloader/dtb
      cp -a $(get_build_dir linux)/arch/$TARGET_KERNEL_ARCH/boot/dts/amlogic/*gxl*.dtb $RELEASE_DIR/3rdparty/bootloader/dtb
      cp -a $(get_build_dir linux)/arch/$TARGET_KERNEL_ARCH/boot/dts/amlogic/*gxm*.dtb $RELEASE_DIR/3rdparty/bootloader/dtb
      ;;
    AMLG12|Odroid_N2)
      cp -a $(get_build_dir linux)/arch/$TARGET_KERNEL_ARCH/boot/dts/amlogic/*g12a*.dtb $RELEASE_DIR/3rdparty/bootloader/dtb
      cp -a $(get_build_dir linux)/arch/$TARGET_KERNEL_ARCH/boot/dts/amlogic/*g12b*.dtb $RELEASE_DIR/3rdparty/bootloader/dtb
      ;;
    all|*)
      cp -a $(get_build_dir linux)/arch/$TARGET_KERNEL_ARCH/boot/dts/amlogic/*.dtb $RELEASE_DIR/3rdparty/bootloader/dtb
      ;;
  esac
