#!/bin/bash

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2019-present Team LibreELEC (https://libreelec.tv)

mkdir -p "$RELEASE_DIR/3rdparty/bootloader"
cp $ROOT/projects/$PROJECT/devices/$DEVICE/bootloader/boot.ini $RELEASE_DIR/3rdparty/bootloader
cp $ROOT/projects/$PROJECT/devices/$DEVICE/bootloader/u-boot.bin $RELEASE_DIR/3rdparty/bootloader
cp $ROOT/projects/$PROJECT/devices/$DEVICE/bootloader/u-boot.bin.sd.bin $RELEASE_DIR/3rdparty/bootloader

mkdir -p "$RELEASE_DIR/3rdparty/bootloader/dtb"
cp -a $(get_build_dir linux)/arch/$TARGET_KERNEL_ARCH/boot/dts/amlogic/*g12b*.dtb $RELEASE_DIR/3rdparty/bootloader/dtb
